Added intermediate example trajectory and abstracted thrust_scalar to launch file
unl-nimbus-lab/Freyja pull request #5
Opened 2020-12-05 18:07 UTC by hildebrandt-carl

1) Changed the circle example trajectory to aggressive_circle (it's terrifying to do in a cage), and added a new circle trajectory that is significantly slower, and possibly a better intermediate stage for testing the setup. Thus the example's provided are now:

* Hover
* Circle
* Aggressive_Circle

2) Added the thrust_scalar parameter to the launch file, as it's a parameter people will need to change frequently with new drones.

3) Miscellaneous stuff e.g. moving type before value to keep consistency across entire launch file, etc.

2020-12-05 23:49 UTC, ajshank commented on freyja_trajectory_provider/src/trajectory_provider.cpp
> +TrajRef getAggressiveCircleReference( const ros::Duration &cur_time )
Make common function: `getCircleReference( const ros::Duration &t, const int agg_level)`

Then, based on `agg_level` (1,2,3..) define values for variables `A` and `w`. `A` is amplitude (radius), `w` angular rate such that `2pi/w` = (seconds for one rev). So, `w=1` means 6.24s, `w=2` means 3.14s etc .. larger `w` ==> faster circles.

Then,
```
pn = A*std::sin( w*t );
pe = A*std::cos( w*t );
: 
vn = A*w*std::cos( w*t );
ve = -A*w*std::sin( w*t );
```

2020-12-05 23:49 UTC, ajshank commented on freyja_trajectory_provider/src/trajectory_provider.cpp
> +  Whatever you do here, output a time-based continuos function to follow.
"continuous" :)

2020-12-05 23:49 UTC, ajshank commented on freyja_controller.launch
> +  <arg name="thrust_scalar" default="200.0"/>
Typo: `thrust_scaler`

2020-12-05 23:52 UTC, ajshank requested changes
Create a different branch for these changes, and let's merge that branch into `master` here.

2020-12-06 17:25 UTC, hildebrandt-carl commented
I am closing this pull request to rebase so that not all 6 commits are present in this pull. I will make the requested changes.

2020-12-06 17:25 UTC, closed without merging